---
- name: Provisionner VM
  hosts: all
  become: yes
  become_method: sudo
  remote_user: ubuntu
  tasks:
      - import_tasks: 2/user_and_group.yml
    # - import_tasks: 3/authorized_keys.yml
      - import_tasks: 2/sudoers.yml
      - import_tasks: 5/Serv BDD/firewall_rules.yml
  handlers:
      - import_tasks: handlers/restart_sshd.yml
