---
- name: Provisionner VM
  hosts: all
  become: yes
  become_method: sudo
  remote_user: ubuntu
  tasks:
      - import_tasks: 2/user_and_group.yml #pour la création de l'utilisateur web et du groupe devops
      - import_tasks: 2/authorized_keys.yml #check la clé publique
      - import_tasks: 2/sudoers.yml #ajout de sudo
      - import_tasks: 3/installation_lamp.yml
      - import_tasks: 4/A_4_installation_wp.yml
      - import_tasks: 5/Serv_WEB/A_5_ufw_install.yml
      - import_tasks: 5/Serv_WEB/A_5_firewall_rules.yml
  handlers:
      - import_tasks: handlers/restart_sshd.yml
