# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "serveur" do |vm1|
    vm1.vm.box = "ubuntu/focal64"
    vm1.vm.network "private_network", ip: "192.168.56.1"
    vm1.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
   end
   
   config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../ansiblesrv/site.yml"
    ansible.compatibility_mode = "2.0"
    ansible.groups = {
      "srv" => ["vm1"]
    }
   end
  end

  config.vm.define "bdd" do |vm2|
    vm2.vm.box = "ubuntu/focal64"
    vm2.vm.network "private_network", ip: "192.168.56.2"
    vm2.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
   end
   
   config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../ansiblebdd/site.yml"
    ansible.compatibility_mode = "2.0"
    ansible.groups = {
      "bdd" => ["vm2"]
    }
   end
  end
end
