---
- name: Provisionner VM
  hosts: all
  become: yes
  become_method: sudo
  remote_user: ubuntu
  tasks:
    #- import_tasks: 2/pam_pwquality.yml
  handlers:
    #- import_tasks: handlers/restart_sshd.yml
